/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_cognito_identity_pool_id:
    "us-east-2:b4699061-42ea-41f8-a6b2-42804d7a84b4",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_uqPJY4aPF",
  aws_user_pools_web_client_id: "56qpnda9q7qnh7com1s86fvap6",
  oauth: {},
};

export default awsmobile;
